name: wheels

on:
  push:
    branches: [ main ]
    paths:
      - "setup.py"
      - ".github/workflows/wheels.yml"

jobs:
  deploy-wheels-to-linux:
    name: Build wheels on Linux for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
        manylinux-image: [manylinux2014]
        arch: [auto, aarch64]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools wheel

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel -U

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: 'cp${{ matrix.python-version }}-*'
          CIBW_SKIP: '*musllinux*'
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_MANYLINUX_*_IMAGE: ${{ matrix.manylinux-image }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux-image }}
      - name: Upload wheels
        continue-on-error: true
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_API_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload wheelhouse/*.whl
